# Generated by Django 3.1.1 on 2020-09-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='producto',
            new_name='name',
        ),
    ]
